name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    uses: kir-dev/automations/.github/workflows/node-ci.yml@node-ci
    with:
      node-version: 20
      package-manager: yarn
      skip-test: true 
      test-script: test:cov
      build-artifacts-path: ./apps/backend/dist
      test-coverage-path: coverage
      working-directory-scripts: ./apps/backend
  
  frontend:
    uses: kir-dev/automations/.github/workflows/node-ci.yml@node-ci
    with:
      node-version: 20
      package-manager: yarn
      skip-test: true 
      test-script: test:cov
      test-coverage-path: coverage
      working-directory-scripts: ./apps/frontend
