name: croned

on:
  schedule:
    - cron: "*/5 * * * *"

env:
  BOT_DRY_RUN: ${{ github.event_name == 'schedule' && 0 || 1 }}

jobs:
  check_prisma_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Foo Bar Baz
        run: echo "${{ env.BOT_DRY_RUN }}"
