name: Parse PR body

on:
  issue_comment:

jobs:
  check_prisma_changes:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Parse start keyword regex
        id: parse_description
        env:
            BODY: ${{ github.event.comment.body }}
            DESCRIPTION: ${{ github.event.issue.body }}
            IGNORE_TESTING_OPTIMIZATION_PATTERN: '- [ ] Ignore testing optimization'
            IGNORE_TESTING_OPTIMIZATION_FLAG: '--ignore-testing-optimization'
        run: |
          #!/bin/bash
          formatted_comment=${BODY//\"/\'}
          if [[ "$formatted_comment" =~ gate-test ]]; then
            echo "RUN_GK=true" >> $GITHUB_ENV
          else
            echo "RUN_GK=false" >> $GITHUB_ENV
          fi

          formated_description=${DESCRIPTION//\"/\'}
          EXTRA_PARAMS=""
          if [[ "$formated_description" == *"${{ env.IGNORE_TESTING_OPTIMIZATION_PATTERN }}"*" ]]; then
            EXTRA_PARAMS="${EXTRA_PARAMS} ${{ env.IGNORE_TESTING_OPTIMIZATION_FLAG }}"
          fi
          echo "EXTRA_PARAMS=$EXTRA_PARAMS" >> "$GITHUB_OUTPUT"
          echo "RUN_GK=$RUN_GK $EXTRA_PARAMS" >> "$GITHUB_STEP_SUMMARY"
      - name: Use the flags
        run: |
          echo  PARAMS="--org ${{ github.event.repository.owner.login }} --repo ${{ github.event.repository.name }} --secrets hwx_secrets.conf ${{ steps.parse_description.outputs.EXTRA_PARAMS }}" sh jenkins.sh

