name: Parse PR body

on:
  issue_comment:
    types: [created, edited]

jobs:
  check_prisma_changes:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Parse start keyword regex
        id: parse_description
        env:
          BODY: ${{ github.event.comment.body }}
          DESCRIPTION: ${{ github.event.issue.body }}
          IGNORE_TESTING_OPTIMIZATION_PATTERN: "- [x] Ignore testing optimization"
          IGNORE_TESTING_OPTIMIZATION_FLAG: "--ignore-testing-optimization"
        run: |
          #!/bin/bash
          formatted_comment=${BODY//\"/\'}
          formated_description=${DESCRIPTION//\"/\'}

          RUN_GK='false'
          if [[ "$formatted_comment" =~ gate-test ]]; then
            RUN_GK=true
          fi
          echo "RUN_GK=$RUN_GK" >> "$GITHUB_ENV"


          EXTRA_PARAMS=""
          if [[ "$formated_description" == *"${{ env.IGNORE_TESTING_OPTIMIZATION_PATTERN }}"* ]]; then
            EXTRA_PARAMS="${EXTRA_PARAMS} ${{ env.IGNORE_TESTING_OPTIMIZATION_FLAG }}"
          fi
          echo "EXTRA_PARAMS=$EXTRA_PARAMS" >> "$GITHUB_OUTPUT"


          echo '# Gatekeeping comment parsing' >> "$GITHUB_STEP_SUMMARY"
          echo '```bash'  >> "$GITHUB_STEP_SUMMARY"
          echo "RUN_GK=$RUN_GK $EXTRA_PARAMS" >> "$GITHUB_STEP_SUMMARY"
          echo '```'  >> "$GITHUB_STEP_SUMMARY"
      - name: Use the flags
        run: |
          echo  PARAMS="--org ${{ github.event.repository.owner.login }} --repo ${{ github.event.repository.name }} --secrets hwx_secrets.conf ${{ steps.parse_description.outputs.EXTRA_PARAMS }}" sh jenkins.sh
