name: Parse PR body

on:
  issue_comment:
    types: [created, edited]

jobs:
  check_prisma_changes:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: parse PR description for testing
        id: parse_pr
        if: ${{ github.event.issue.pull_request }}
        env:
          DESCRIPTION: ${{ github.event.issue.body }}
          IGNORE_TESTING_OPTIMIZATION_PATTERN: "- [x] Ignore testing optimization"
          IGNORE_TESTING_OPTIMIZATION_FLAG: "--ignore-relaunch-check"
        run: |
          formatted_description=${DESCRIPTION//\"/\'}
          EXTRA_PARAMS=""
          if [[ "$formatted_description" == *"${{ env.IGNORE_TESTING_OPTIMIZATION_PATTERN }}"* ]]; then
            EXTRA_PARAMS="${EXTRA_PARAMS} ${{ env.IGNORE_TESTING_OPTIMIZATION_FLAG }}"
          fi
          echo "EXTRA_PARAMS=$EXTRA_PARAMS" >> "$GITHUB_OUTPUT"
      - name: foo
        id: skipped
        if: cancelled()
        run: echo CODE=123 >> $GITHUB_OUTPUT
      - name: Use the flags
        run: |
          echo  PARAMS="--skipped_code=${{ steps.skipped.outputs.CODE }} --org ${{ github.event.repository.owner.login }} --repo ${{ github.event.repository.name }} --secrets hwx_secrets.conf ${{ steps.parse_description.outputs.EXTRA_PARAMS }}" sh jenkins.sh
